//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/ControllerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControllerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControllerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControllerInput"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""6ea360be-684e-4b7e-a696-79da4aaf5588"",
            ""actions"": [
                {
                    ""name"": ""SouthButton"",
                    ""type"": ""Button"",
                    ""id"": ""a4370d10-2a5b-458a-888a-113ef313cfea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EastButton"",
                    ""type"": ""Button"",
                    ""id"": ""4446dd60-5974-413a-bfb5-8c87f0fef8b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NorthButton"",
                    ""type"": ""Button"",
                    ""id"": ""80066e51-6ebb-4296-8b48-6bde94f6e518"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WestButton"",
                    ""type"": ""Button"",
                    ""id"": ""ef704897-e9e9-426d-8733-42783d7e2099"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DpadUp"",
                    ""type"": ""Button"",
                    ""id"": ""0567b873-ba62-46cd-9497-b4db09cab9a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DpadDown"",
                    ""type"": ""Button"",
                    ""id"": ""8e4df65b-5ed7-4028-b9ca-619d04d4b74d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DpadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""6d56156b-5fbe-4fd6-8c5f-251991447389"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DpadRight"",
                    ""type"": ""Button"",
                    ""id"": ""2554f5df-f761-4e63-921f-ba046f907036"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""a70902d6-c839-4c84-8b8e-06f749db6215"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""0d7da876-b255-40d6-a44b-9707001d436e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""ee59a27a-8830-43d6-a6cc-3473b4eccf00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Button"",
                    ""id"": ""c3287bfa-040c-4049-b4e7-aea2b8730f98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""b6af9b5e-22d8-4277-b6f2-f9d0ab7e18cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""1935848e-8c5e-44ab-aaa9-2d6e0f8ca8b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LStick"",
                    ""type"": ""Value"",
                    ""id"": ""9a67c315-92e4-4caa-8b6f-e4dbf9fbb44b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""New action"",
                    ""type"": ""Value"",
                    ""id"": ""63807f87-58fb-4d0d-8bd6-2cda8cf22a73"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LStickPress"",
                    ""type"": ""Button"",
                    ""id"": ""5319214d-7fd3-46c1-83e7-7f78600cf47b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RStickPress"",
                    ""type"": ""Button"",
                    ""id"": ""c5f13c4b-91a3-4589-8308-79c78f21796f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RStick"",
                    ""type"": ""Value"",
                    ""id"": ""ffff60c3-009d-49b8-a948-7bf4f35f7175"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9e4b391d-0edc-4771-b540-a8a448c6eb4d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SouthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a485856-f517-4a81-8018-4e9e2691d456"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EastButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""270c0171-ac7f-4433-82c5-194e040e9587"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NorthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ca5352a-2efe-4009-8b23-de725ee37739"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WestButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a727541e-4587-4114-a9f5-389b97a46c0c"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DpadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73bb6ade-ad71-43fd-aa37-5fe1725770c5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DpadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccb7b46f-919c-4f11-8635-e19d48194f65"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DpadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1285ee8-bb53-49d4-ab20-663b0f5d63d9"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10f6175f-4e37-4742-a337-3455e343462b"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cdd67033-86a9-4565-961e-05f2801042a7"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c405280-70fe-4a32-b8fd-0a4d78d6cf11"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbb39761-635b-473f-a9ee-1d342d4968f3"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e198a83f-2c0c-4469-8c07-9086bce14fc3"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f57910c-9743-4c31-9a58-4e1724c2dbed"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DpadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8790a216-e651-4479-95fd-30c0ac3fb80f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e745a36-d79f-47e9-b052-120f0ddbcd15"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bf4e8d3-ae37-4184-b4b9-ceb8f5cee3bf"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68dbfa1b-b849-4118-9a5a-bf06be8efeec"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2313126-27c3-40b2-9872-777e926033fb"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_SouthButton = m_Gameplay.FindAction("SouthButton", throwIfNotFound: true);
        m_Gameplay_EastButton = m_Gameplay.FindAction("EastButton", throwIfNotFound: true);
        m_Gameplay_NorthButton = m_Gameplay.FindAction("NorthButton", throwIfNotFound: true);
        m_Gameplay_WestButton = m_Gameplay.FindAction("WestButton", throwIfNotFound: true);
        m_Gameplay_DpadUp = m_Gameplay.FindAction("DpadUp", throwIfNotFound: true);
        m_Gameplay_DpadDown = m_Gameplay.FindAction("DpadDown", throwIfNotFound: true);
        m_Gameplay_DpadLeft = m_Gameplay.FindAction("DpadLeft", throwIfNotFound: true);
        m_Gameplay_DpadRight = m_Gameplay.FindAction("DpadRight", throwIfNotFound: true);
        m_Gameplay_L1 = m_Gameplay.FindAction("L1", throwIfNotFound: true);
        m_Gameplay_L2 = m_Gameplay.FindAction("L2", throwIfNotFound: true);
        m_Gameplay_R1 = m_Gameplay.FindAction("R1", throwIfNotFound: true);
        m_Gameplay_R2 = m_Gameplay.FindAction("R2", throwIfNotFound: true);
        m_Gameplay_Start = m_Gameplay.FindAction("Start", throwIfNotFound: true);
        m_Gameplay_Select = m_Gameplay.FindAction("Select", throwIfNotFound: true);
        m_Gameplay_LStick = m_Gameplay.FindAction("LStick", throwIfNotFound: true);
        m_Gameplay_Newaction = m_Gameplay.FindAction("New action", throwIfNotFound: true);
        m_Gameplay_LStickPress = m_Gameplay.FindAction("LStickPress", throwIfNotFound: true);
        m_Gameplay_RStickPress = m_Gameplay.FindAction("RStickPress", throwIfNotFound: true);
        m_Gameplay_RStick = m_Gameplay.FindAction("RStick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_SouthButton;
    private readonly InputAction m_Gameplay_EastButton;
    private readonly InputAction m_Gameplay_NorthButton;
    private readonly InputAction m_Gameplay_WestButton;
    private readonly InputAction m_Gameplay_DpadUp;
    private readonly InputAction m_Gameplay_DpadDown;
    private readonly InputAction m_Gameplay_DpadLeft;
    private readonly InputAction m_Gameplay_DpadRight;
    private readonly InputAction m_Gameplay_L1;
    private readonly InputAction m_Gameplay_L2;
    private readonly InputAction m_Gameplay_R1;
    private readonly InputAction m_Gameplay_R2;
    private readonly InputAction m_Gameplay_Start;
    private readonly InputAction m_Gameplay_Select;
    private readonly InputAction m_Gameplay_LStick;
    private readonly InputAction m_Gameplay_Newaction;
    private readonly InputAction m_Gameplay_LStickPress;
    private readonly InputAction m_Gameplay_RStickPress;
    private readonly InputAction m_Gameplay_RStick;
    public struct GameplayActions
    {
        private @ControllerInput m_Wrapper;
        public GameplayActions(@ControllerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @SouthButton => m_Wrapper.m_Gameplay_SouthButton;
        public InputAction @EastButton => m_Wrapper.m_Gameplay_EastButton;
        public InputAction @NorthButton => m_Wrapper.m_Gameplay_NorthButton;
        public InputAction @WestButton => m_Wrapper.m_Gameplay_WestButton;
        public InputAction @DpadUp => m_Wrapper.m_Gameplay_DpadUp;
        public InputAction @DpadDown => m_Wrapper.m_Gameplay_DpadDown;
        public InputAction @DpadLeft => m_Wrapper.m_Gameplay_DpadLeft;
        public InputAction @DpadRight => m_Wrapper.m_Gameplay_DpadRight;
        public InputAction @L1 => m_Wrapper.m_Gameplay_L1;
        public InputAction @L2 => m_Wrapper.m_Gameplay_L2;
        public InputAction @R1 => m_Wrapper.m_Gameplay_R1;
        public InputAction @R2 => m_Wrapper.m_Gameplay_R2;
        public InputAction @Start => m_Wrapper.m_Gameplay_Start;
        public InputAction @Select => m_Wrapper.m_Gameplay_Select;
        public InputAction @LStick => m_Wrapper.m_Gameplay_LStick;
        public InputAction @Newaction => m_Wrapper.m_Gameplay_Newaction;
        public InputAction @LStickPress => m_Wrapper.m_Gameplay_LStickPress;
        public InputAction @RStickPress => m_Wrapper.m_Gameplay_RStickPress;
        public InputAction @RStick => m_Wrapper.m_Gameplay_RStick;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @SouthButton.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSouthButton;
                @SouthButton.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSouthButton;
                @SouthButton.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSouthButton;
                @EastButton.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnEastButton;
                @EastButton.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnEastButton;
                @EastButton.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnEastButton;
                @NorthButton.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnNorthButton;
                @NorthButton.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnNorthButton;
                @NorthButton.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnNorthButton;
                @WestButton.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnWestButton;
                @WestButton.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnWestButton;
                @WestButton.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnWestButton;
                @DpadUp.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadUp;
                @DpadUp.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadUp;
                @DpadUp.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadUp;
                @DpadDown.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadDown;
                @DpadDown.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadDown;
                @DpadDown.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadDown;
                @DpadLeft.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadLeft;
                @DpadLeft.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadLeft;
                @DpadLeft.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadLeft;
                @DpadRight.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadRight;
                @DpadRight.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadRight;
                @DpadRight.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDpadRight;
                @L1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL1;
                @L1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL1;
                @L1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL1;
                @L2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL2;
                @L2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL2;
                @L2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL2;
                @R1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR1;
                @R1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR1;
                @R1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR1;
                @R2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR2;
                @R2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR2;
                @R2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR2;
                @Start.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnStart;
                @Select.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSelect;
                @LStick.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLStick;
                @LStick.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLStick;
                @LStick.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLStick;
                @Newaction.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnNewaction;
                @LStickPress.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLStickPress;
                @LStickPress.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLStickPress;
                @LStickPress.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLStickPress;
                @RStickPress.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRStickPress;
                @RStickPress.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRStickPress;
                @RStickPress.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRStickPress;
                @RStick.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRStick;
                @RStick.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRStick;
                @RStick.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRStick;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SouthButton.started += instance.OnSouthButton;
                @SouthButton.performed += instance.OnSouthButton;
                @SouthButton.canceled += instance.OnSouthButton;
                @EastButton.started += instance.OnEastButton;
                @EastButton.performed += instance.OnEastButton;
                @EastButton.canceled += instance.OnEastButton;
                @NorthButton.started += instance.OnNorthButton;
                @NorthButton.performed += instance.OnNorthButton;
                @NorthButton.canceled += instance.OnNorthButton;
                @WestButton.started += instance.OnWestButton;
                @WestButton.performed += instance.OnWestButton;
                @WestButton.canceled += instance.OnWestButton;
                @DpadUp.started += instance.OnDpadUp;
                @DpadUp.performed += instance.OnDpadUp;
                @DpadUp.canceled += instance.OnDpadUp;
                @DpadDown.started += instance.OnDpadDown;
                @DpadDown.performed += instance.OnDpadDown;
                @DpadDown.canceled += instance.OnDpadDown;
                @DpadLeft.started += instance.OnDpadLeft;
                @DpadLeft.performed += instance.OnDpadLeft;
                @DpadLeft.canceled += instance.OnDpadLeft;
                @DpadRight.started += instance.OnDpadRight;
                @DpadRight.performed += instance.OnDpadRight;
                @DpadRight.canceled += instance.OnDpadRight;
                @L1.started += instance.OnL1;
                @L1.performed += instance.OnL1;
                @L1.canceled += instance.OnL1;
                @L2.started += instance.OnL2;
                @L2.performed += instance.OnL2;
                @L2.canceled += instance.OnL2;
                @R1.started += instance.OnR1;
                @R1.performed += instance.OnR1;
                @R1.canceled += instance.OnR1;
                @R2.started += instance.OnR2;
                @R2.performed += instance.OnR2;
                @R2.canceled += instance.OnR2;
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @LStick.started += instance.OnLStick;
                @LStick.performed += instance.OnLStick;
                @LStick.canceled += instance.OnLStick;
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
                @LStickPress.started += instance.OnLStickPress;
                @LStickPress.performed += instance.OnLStickPress;
                @LStickPress.canceled += instance.OnLStickPress;
                @RStickPress.started += instance.OnRStickPress;
                @RStickPress.performed += instance.OnRStickPress;
                @RStickPress.canceled += instance.OnRStickPress;
                @RStick.started += instance.OnRStick;
                @RStick.performed += instance.OnRStick;
                @RStick.canceled += instance.OnRStick;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnSouthButton(InputAction.CallbackContext context);
        void OnEastButton(InputAction.CallbackContext context);
        void OnNorthButton(InputAction.CallbackContext context);
        void OnWestButton(InputAction.CallbackContext context);
        void OnDpadUp(InputAction.CallbackContext context);
        void OnDpadDown(InputAction.CallbackContext context);
        void OnDpadLeft(InputAction.CallbackContext context);
        void OnDpadRight(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnL2(InputAction.CallbackContext context);
        void OnR1(InputAction.CallbackContext context);
        void OnR2(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnLStick(InputAction.CallbackContext context);
        void OnNewaction(InputAction.CallbackContext context);
        void OnLStickPress(InputAction.CallbackContext context);
        void OnRStickPress(InputAction.CallbackContext context);
        void OnRStick(InputAction.CallbackContext context);
    }
}
